Add authentication option to race list
racetimeGG/racetime-app pull request #119
Opened 2021-04-09 23:40 UTC by Killklli

Allows users to view unlisted races if they are authenticated

2021-04-10 11:21 UTC, deains reviewed
This is a bit of a roundabout way to list out the races. I don't think it's necessary to run two queries here, and it certainly isn't necessary to iterate over the unlisted races like you've done here. Instead you can do something like this:

```py
unlisted_filter = Q(unlisted=False)
if self.request.user.is_authenticated:
    unlisted_filter |= Q(unlisted=True, entrant__user=self.request.user)

races = models.Race.objects.filter(
    category__active=True,
).filter(unlisted_filter).exclude(state__in=[
    models.RaceStates.finished,
    models.RaceStates.cancelled,
])
```

2021-04-16 11:50 UTC, deains requested changes
Got some notes and thoughts below. 🙂 Very much looking forward to seeing the LiveSplit side of this!

2021-04-16 11:50 UTC, deains commented on racetime/templates/racetime/race_livesplit.html
> +</style>
This section is a bit of a mess, could you clear it up a little? I think the `<meta>` tags are unnecessary here.

2021-04-16 11:50 UTC, deains commented on racetime/views/__init__.py
> +    'RaceLivesplit',
Pedantic, but it should really be `LiveSplit`.

2021-04-16 11:50 UTC, deains commented on racetime/views/race.py
> +    template_name_suffix = '_livesplit'
I think we should probably restrict this view to authenticated users only. I don't see any need for it if you're logged out, and it's not something I want Google to stumble on.

2021-04-16 11:50 UTC, deains commented on racetime/views/race.py
> +    required_scopes = ['chat_delete']
I think you should use the existing `race_action` scope for this.

2021-04-16 11:50 UTC, deains commented on racetime/views/race.py
> +        })
There's obviously quite a bit of duplication here with `RaceChatDelete`, could you look into DRYing it up a little?

2021-04-16 11:50 UTC, deains commented on racetime/views/race.py
> +class OAuthRaceChatPurge(ScopedProtectedResourceView, BotMixin, RaceChatMixin):
Ditto the above remarks on this view.

2021-04-16 19:21 UTC, Killklli commented
Also this deals with https://github.com/racetimeGG/racetime-app/issues/78 and https://github.com/racetimeGG/racetime-app/issues/48 and a handful of other issues not loaded into git

2021-04-17 07:53 UTC, merged